config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('gis_app.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gis_app/urls.py
from django.urls import path
from .views import (
        MarkerMapView, SignInView, SignUpView, 
        LogOutView, ProfileView, UserListView,
        UserView, Where, ListImageView
    )

app_name = 'gis_app'

urlpatterns = [
    path('', MarkerMapView.as_view(), name='marker'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user/<int:pk>/', UserView.as_view(), name='user'),
    path('user/list/', UserListView.as_view(), name='users_list'),
    path('where/', Where.as_view(), name='where'),
    path('images/list/<int:pk>/', ListImageView.as_view(), name='image_list'),
]

templates/include/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'gis_app:profile' %}">Profile</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'gis_app:marker' %}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gis_app:logout' %}">LogOut</a>
          </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'gis_app:signin' %}">SignIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gis_app:signup' %}">SignUp</a>
          </li>
        {% endif %}
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'gis_app:users_list' %}">Users</a>
        </li>
        <!-- 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        -->
      </ul>
      <form action="{% url 'gis_app:where' %}" method="GET" class="form-inline my-2 my-lg-0">
        <input  class="form-control mr-sm-2" placeholder="city name search ..." type="search" name="name" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>