config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('gis_app.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gis_app/urls.py
from django.urls import path
from .views import (
        MarkerMapView, SignInView, SignUpView, 
        LogOutView, ProfileView, UserListView,
        UserView, Where, ListImageView
    )

app_name = 'gis_app'

urlpatterns = [
    path('', MarkerMapView.as_view(), name='marker'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user/<int:pk>/', UserView.as_view(), name='user'),
    path('user/list/', UserListView.as_view(), name='users_list'),
    path('where/', Where.as_view(), name='where'),
    path('images/list/<int:pk>/', ListImageView.as_view(), name='image_list'),
]

gis_app/models.py
from django.contrib.gis.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)
    home = models.PointField()
    worker = models.PointField()
    city = models.PolygonField()

    def __str__(self):
        return f'{self.user.username}-{self.id}'

    @property
    def city_point_list(self):
        return [[point.x, point.y] for point in self.city]


class Marker(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date = models.DateTimeField()
    location = models.PointField()

    def __str__(self):
        return self.name


class MarkerImage(models.Model):
    msrker = models.ForeignKey(Marker, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'marker/')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
   integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
   crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
    integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ==" crossorigin="">
  </script>
  <link rel="stylesheet" href="{% static 'map.css' %}">
  <title>Document</title>
</head>
<body>
    {% include 'include/nav.html' %}
    {% block body %} ;;;;{% endblock %}

    {% block js %} {% endblock %}
</body>
</html>

templates/form.html
{% extends 'base.html' %}
{% load static %}

{%  block body %}
    <div class="col-4"></div>
    <form method="POST" novalidate class="col-6">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group row">
              <label for="inputPassword" class="col-sm-2 col-form-label">{{ field.label }}</label>
              <div class="col-sm-10">
                {{ field }}
                <h5 class="alert-danger">{{ field.errors }}</h5>
            </div>
            </div>
        {% endfor %}
        <input class="btn btn-outline-primary my-2 my-sm-0" type="submit" value="Save">

    </form>

   
{% endblock %}

templates/marker.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
  <div id="map" class="col-9"></div>
{% endblock %}

{% block js %}
  <script src="{% static 'map.js' %}"></script>
  
  <script>
    {% for data in marker_list %}
      var marker = L.marker({{ data.location }}).addTo(map);
      marker.bindPopup("{{ data.name }}-{{ data.date }}").openPopup();
    {% endfor %}
  </script>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<div class="row">
  <div id="map" class="col-9 border border-primary m-2" style="height: 700px"></div>
  <div id="map" class="col-2 text-justify border border-success m-2">
  <p>User Description {{ information.username }}</p>
    {{information.description}}
  </div>
</div>
{% endblock %}

{% block js %}
  <script src="{% static 'map.js' %}"></script>
  <script>
    var home = L.marker({{ information.home }}).addTo(map);
    var worker = L.marker({{ information.worker }}).addTo(map);
    home.bindPopup("Home").openPopup();
    worker.bindPopup("Work").openPopup();

    var myLines = [{
        "type": "LineString",
        "coordinates": {{information.line}}
    }, ];

    var myStyle = {
        "color": "#ff7800",
        "weight": 5,
        "opacity": 0.65,
    };
    
    L.geoJSON(myLines, {
        style: myStyle,
        onEachFeature: function (feature,layer) { 
          layer.bindPopup('');
          layer.on('popupopen', function(e) {
            var popup = e.popup;
            popup.setContent("length of two local:<br/> {{information.length}} km");
          });
        }
    }).addTo(map);

    var city = L.polygon(
      
      
    ).addTo(map);

  </script>
{% endblock %}

templates/users.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
  <div id="map" ></div>
 
{% endblock %}

{% block js %}
    <script src="{% static 'map.js' %}"></script>
    <script>
        {% for user in users %}
            var user = L.marker([{{ user.home.y }}, {{ user.home.x }}]).addTo(map);
            user.bindPopup("<a href='{% url 'gis_app:user' user.user.id %}'>{{ user.user.username }}</a>").openPopup();
        {% endfor %}
    </script>
{% endblock %}

templates/where.html
{% extends 'base.html' %}
{% load static %}

{%  block body %}
<div id="map" class="col-9 border border-primary m-2" style="height: 700px">
    {{ map|safe }}

</div>


    {% endblock %}